### ISSUE TITLE
Template should write the first commit message as "feat: initial commit"

### ISSUE THREAD

**Issue by scorpion9979** [paulrberg/hardhat-template#104]
Currently when using the template, it produces the first commit message in the created repo as "Initial commit". My proposal is to change it to "feat: initial commit", so as to remain consistent with the conventional commits specification.

**Comment by paulrberg** [comment]
I actually don't know how to do this. I asked for help on [StackOverflow](https://stackoverflow.com/questions/71723842/how-to-change-the-default-first-commit-message-when-using-a-github-template), and I also contacted GitHub via their support channel. I will follow up here once I find out the solution - if there is one!

**Comment by zinderud** [comment]
I error to
⧗   input: Hello World!
✖   subject may not be empty [subject-empty]
✖   type may not be empty [type-empty]

✖   found 2 problems, 0 warnings
ⓘ   Get help: https://github.com/conventional-changelog/commitlint/#what-is-commitlint

husky > commit-msg hook failed (add --no-verify to bypass)

**Comment by paulrberg** [comment]
@zinderud this template enforces [conventional commits](https://www.conventionalcommits.org/en/v1.0.0-beta.4/). You can read the full specification [here](https://www.conventionalcommits.org/en/v1.0.0-beta.4/#specification).

You cannot write "Hello World" as a commit message - it will have to be "feat: hello world".

**Comment by Janther** [comment]
I have an idea where by using a GitHub action that runs just once when the template is used for a new repo.
We could replace some values like repo links and maybe replace the `package.json` author and other details like the badges in the readme.
And auto commit with `--amend` and a new commit message `feat: initial commit`.
Any thoughts?

**Comment by paulrberg** [comment]
Ah, this would very interesting. Great idea @Janther. We could take inspiration from the [femplate](https://github.com/abigger87/femplate/blob/2f3e1b2c630acdb2b3e5e31a6dc25d31b5a5e48b/utils/rename.sh) Foundry template on how do to the initial renaming.
