### ISSUE TITLE
Replace Rinkeby network config with Goerli

### ISSUE THREAD

**Issue by scorpion9979** [paulrberg/hardhat-template#131]
Rinkeby testnet is getting deprecated next month, along with a few other testnets. Goerli is going to be one of the very few Ethereum testnets that will survive the merge. I suggest removing the Rinkeby network config and replacing it with Goerli.

**Comment by paulrberg** [comment]
Good catch! Do you know whether Polygon Mumbai will get deprecated too?

**Comment by scorpion9979** [comment]
@paulrberg I couldn't find any news on Polygon Mumbai. I think it's safe to assume it will still be around for now.

**Comment by paulrberg** [comment]
Fair enough, thanks for taking a look anyway.

And thanks for your contribution!
