### ISSUE TITLE
change template contract

### ISSUE THREAD

**Issue by yash251** [PaulRBerg/hardhat-template#141]
Hardhat now has changed the base contract of Greeter.sol to Lock.sol

**Comment by paulrberg** [comment]
Thanks for the heads-up! I will probably stick with `Greeter` for the time being, because refactoring the template to use `Lock` would take some time and unfortunately I don't have the bandwidth to do that now.

PRs welcome.

**Comment by paulrberg** [comment]
Thanks @jonahcui, I have provided feedback on the PR.
