### ISSUE TITLE
pnpm install : unmet peer @types/mocha@^9.1.0: found 10.0.0

### ISSUE THREAD

**Issue by SvenMeyer** [PaulRBerg/hardhat-template#160]
Just grabbed a fresh copy of the template, did `pnpm install`, got a few warning and at the end ..
```

 WARN  Issues with peer dependencies found
.
└─┬ @nomicfoundation/hardhat-toolbox 2.0.0
  └── ✕ unmet peer @types/mocha@^9.1.0: found 10.0.0
```

Anything to be concerned about ?

**Comment by PaulRBerg** [comment]
Not sure because I have not been using this template for a long time; I have switched all of my Solidity projects to Foundry.

@DenhamPreen might be able to help here.

**Comment by wiasliaw** [comment]
Hi, @SvenMeyer

It can be solved by downgrading the `@types/mocha`'s version to 9.1.0 or 9.1.1.
It seems that `@nomicfoundation/hardhat-toolbox 3.0.0` had solved this warning.

https://github.com/NomicFoundation/hardhat/blob/4caefa5141c25f9cdc22b44698c0a7ccc7b0e9b8/packages/hardhat-toolbox/package.json#L49

**Comment by PaulRBerg** [comment]
Thanks @wiasliaw - could you make a PR? 🙏

**Comment by wiasliaw** [comment]
> could you make a PR? 

The semver version of the repo is correct and latest. No need to make a PR. The warning is from `nomicfoundation/hardhat-toolbox@2.0.0` which semver version excludes `10.X.X`.

**Comment by PaulRBerg** [comment]
Great, thanks for confirming @wiasliaw. In this case, should we close this issue?

**Comment by wiasliaw** [comment]
Yes, we should.
