### ISSUE TITLE
update hardhat [ContractFactory deploy fails to estimate gas on solidity version: "0.8.20" with Shanghai as default]

### ISSUE THREAD

**Issue by SvenMeyer** [PaulRBerg/hardhat-template#162]
We may want to update hardhat to the latest version as it fixes the problem with solidity version: "0.8.20" with Shanghai as default.

https://github.com/NomicFoundation/hardhat/issues/3977#issuecomment-1576353394

**Comment by PaulRBerg** [comment]
Has this issue been addressed by https://github.com/PaulRBerg/hardhat-template/pull/164, @SvenMeyer?

**Comment by SvenMeyer** [comment]
Yes, have been fixed with an update of hardhat.
