### ISSUE TITLE
running tests doesn't work on test networks

### ISSUE THREAD

**Issue by bullishgopher** [PaulRBerg/hardhat-template#166]
If I run the tests on the hardhat local network, it works fine.
But if I try it on `Goerli` or `Sepolia` network, it fails due to `"@nomicfoundation/hardhat-network-helpers"` package.
Can you please provide me with a solution? @PaulRBerg 

<img width="1161" alt="image" src="https://github.com/PaulRBerg/hardhat-template/assets/49041460/3b8be485-2afa-45e6-88b7-93fa5a7408d4">

**Comment by PaulRBerg** [comment]
You should ask for help in the [Hardhat Discord server](https://discord.com/invite/TETZs2KK4k).

**Comment by bullishgopher** [comment]
Ok, thanks
