### ISSUE TITLE
Add a "Contributors" section in the README

### ISSUE THREAD

**Issue by PaulRBerg** [PaulRBerg/hardhat-template#67]
Which contains the profile pictures of the contributors. See how [standard-readme](https://github.com/RichardLitt/standard-readme) does it:

<img width="826" alt="Capture d’écran 2021-09-13 à 14 34 33" src="https://user-images.githubusercontent.com/8782666/133076550-2e1b35b1-5778-4641-bc20-95472e73260f.png">

**Comment by phyBrackets** [comment]
https://github.com/paulrberg/solidity-template/pull/75

**Comment by PaulRBerg** [comment]
I've changed my mind about this feature.

Because this is a template, the README file will end up in all users' instantiated repo. I would prefer not to clutter those repos with the names of the template contributors (who could be misunderstood to be the contributors to those other repos).
