### ISSUE TITLE
Find a smarter way to keep types and factories in version control

### ISSUE THREAD

**Issue by paulrberg** [paulrberg/hardhat-template#99]
The current approach takes a lot of maintenance, since it involves manually listing the types and the factories in `.gitignore`.

See the discussion started by Sebastian here: https://github.com/paulrberg/solidity-template/discussions/96.

**Comment by Janther** [comment]
Do you think that this should be closed after the improvements on the automated type generation scripts?

**Comment by paulrberg** [comment]
Yeah, it should. Thanks for the heads-up!
